# Generated by Django 5.2.3 on 2025-07-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='myText',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
